### ISSUE TITLE
Error while setting up cox_sensor platform for sensor

### ISSUE THREAD

**Issue by backslashV** [dcshoecomp/homeassistant-cox#10]
```
Error while setting up cox_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/cox_sensor/sensor.py", line 138, in state
    return self._state
AttributeError: 'cox_sensor' object has no attribute '_state'
```
Version | core-2021.4.3
-- | --
Installation Type | Home Assistant OS
Operating System Version | 5.4.83-v8

Any ideas how to fix?

**Comment by dcshoecomp** [comment]
> ```
> Error while setting up cox_sensor platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
>     sstate = self.state
>   File "/config/custom_components/cox_sensor/sensor.py", line 138, in state
>     return self._state
> AttributeError: 'cox_sensor' object has no attribute '_state'
> ```
> 
> Version	core-2021.4.3
> Installation Type	Home Assistant OS
> Operating System Version	5.4.83-v8
> Any ideas how to fix?

Let me pull down my latest release to make sure it matches the code I am running on mine. It seems to still be functioning for me. I will get back to you.

**Comment by dcshoecomp** [comment]
> ```
> Error while setting up cox_sensor platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
>     sstate = self.state
>   File "/config/custom_components/cox_sensor/sensor.py", line 138, in state
>     return self._state
> AttributeError: 'cox_sensor' object has no attribute '_state'
> ```
> 
> Version	core-2021.4.3
> Installation Type	Home Assistant OS
> Operating System Version	5.4.83-v8
> Any ideas how to fix?

I was unable to replicate your issue. Re-Download the latest release version and try setting up the sensor again. My only other thought is that it cannot find your internet plan.
If it still doesn't work log in cox.net and browse to https://www.cox.com/internettools/data-usage.html right click and view page source. Send me that source so I can see how your datapage differs.

**Comment by backslashV** [comment]
Thanks so much for following up. Turns out I was using my old cox username and password. You saying the plan can't be found was a huge hint. Thank you again for your time.
