### ISSUE TITLE
Error: strptime() argument 1 must be str, not None

### ISSUE THREAD

**Issue by rgroce** [dcshoecomp/homeassistant-cox#9]
Just noticed this error in Home Assistant today

Logger: custom_components.cox_sensor.sensor
Source: custom_components/cox_sensor/sensor.py:116
Integration: cox_sensor (documentation)
First occurred: 11:02:57 AM (4 occurrences)
Last logged: 11:03:25 AM

strptime() argument 1 must be str, not None

**Comment by dcshoecomp** [comment]
> Just noticed this error in Home Assistant today
> 
> Logger: custom_components.cox_sensor.sensor
> Source: custom_components/cox_sensor/sensor.py:116
> Integration: cox_sensor (documentation)
> First occurred: 11:02:57 AM (4 occurrences)
> Last logged: 11:03:25 AM
> 
> strptime() argument 1 must be str, not None

Cox killed the ajax that gave us the json with all the raw data. Will have to totally revamp it to use web scraping instead.

**Comment by dcshoecomp** [comment]
New release should fix the issue.
